# Generated by Django 3.0 on 2021-06-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('ParentID', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
